### ISSUE TITLE
Docker ERR_NAME_RESOLUTION_FAILED for swagger.json with Nginx

### ISSUE THREAD

**Issue by 5hirish** [noirbizarre/flask-restplus#670]
Nginx fails to resolve the `swagger.json` correctly. Instead of resolving to `http://127.0.0.1/swagger.json` it resolves to `http://flask_upstream/swagger.json`hence raising the `net::ERR_NAME_RESOLUTION_FAILED` error with docker-compose.
Follownig is the config server block:
```
upstream flask_upstream {
    server flask_server:8000;
}

server {
    listen 80;

    server_name localhost;

    location / {
        proxy_pass http://flask_upstream;
    }
}
```
docker-compose.yaml
```
....
  flask_server:
    image: foobar_api_server:latest
    build:
      context: .
      dockerfile: Dockerfile-apiapp
    container_name: flask
    restart: unless-stopped
    expose:
      - "8000"
    depends_on:
    - postgres_database
    - rabbitmq_message_broker
    volumes:
    - logs:/foobar/logs
    env_file:
    - .env

  nginx_reverse_proxy:
    image: nginx:mainline
    container_name: nginx
    restart: always
    ports:
    - "80:80"
    - "443:443"
    depends_on:
      - flask_server
    volumes:
    - ./nginx:/etc/nginx/conf.d
....
````
